dist: trusty
sudo: required
services:
  - docker
language: go
go:
  - "1.14.x"

script:
  - make vet
  - make test
  - make website-test

env:
  - GO111MODULE=off

branches:
  only:
    - master
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
